name: Test GITHUB_TOKEN

on:
  push:
    branches: [ "main" ]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test GITHUB_TOKEN with API call
      run: |
        curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/actions/secrets
